In [189]:
import pandas as pd

In [190]:
away = pd.read_csv("shots.csv")     
arenas = pd.read_csv("arenas.csv")

In [191]:
merged = away.merge(
    arenas.add_prefix("arena_"),
    left_on="homeMarket",
    right_on="arena_School",
    how="left",
    validate="m:1"
)

# (Optional) sanity: make sure all homes matched an arena
unmatched = merged["arena_School"].isna().sum()
print(f"Unmatched home teams: {unmatched}")

Unmatched home teams: 38944

In [192]:
merged[merged["arena_School"].isna()]["homeMarket"].unique()

array(['SFA', 'Southeastern La.', 'Lamar University', 'UIW',
       'A&M-Corpus Christi', 'Northwestern St.', 'Central Ark.',
       'Sam Houston', 'BYU', 'Abilene Christian', 'Boise St.',
       "Saint Mary's (CA)", 'Colorado St.', 'Utah St.', 'San Jose St.',
       'UNLV', 'Fresno St.', 'San Diego St.', 'LMU (CA)',
       'Cal St. Fullerton', 'CSU Bakersfield', 'CSUN', 'Long Beach St.',
       'Washington St.', 'Oregon St.'], dtype=object)

In [193]:
merged

,gameId,homeMarket,awayMarket,secsIntoGame,teamMarket,actionType,subType,success,side,shotDist,zones6,zones13,season,team,Year,conf,similar_team,half,primary_side,side_mismatch,arena_School,arena_Conference,arena_Wall Number,arena_Side,arena_Distance,arena_Type of Wall,arena_Arena,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type
0,2549421,East Texas A&M,Nicholls,52.0,Nicholls,2pt,stepbackjumpshot,True,LEFT,15.719,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
1,2549421,East Texas A&M,Nicholls,122.0,Nicholls,3pt,jumpshot,False,LEFT,25.014,atb3,rw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
2,2549421,East Texas A&M,Nicholls,391.0,Nicholls,2pt,pullupjumpshot,True,LEFT,11.751,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
3,2549421,East Texas A&M,Nicholls,506.0,Nicholls,3pt,jumpshot,False,LEFT,28.561,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
4,2549421,East Texas A&M,Nicholls,694.0,Nicholls,2pt,turnaroundjumpshot,False,LEFT,13.229,paint2,paint2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90816,2531544,UC Irvine,Cal Poly,1213.0,Cal Poly,3pt,jumpshot,False,RIGHT,23.435,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90817,2531544,UC Irvine,Cal Poly,1354.0,Cal Poly,3pt,jumpshot,True,RIGHT,26.160,atb3,tok3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90818,2531544,UC Irvine,Cal Poly,1407.0,Cal Poly,2pt,pullupjumpshot,True,RIGHT,11.017,paint2,paint2,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90819,2531544,UC Irvine,Cal Poly,1482.0,Cal Poly,3pt,jumpshot,False,RIGHT,25.577,atb3,rw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90820,2531544,UC Irvine,Cal Poly,1517.0,Cal Poly,2pt,turnaroundjumpshot,False,RIGHT,8.051,paint2,paint2,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN

In [194]:
correct_zones = ['le2', 'lw3', 'rw3', 'tok3', 're2', 'heave3']

In [195]:
merged = merged[merged["zones13"].isin(correct_zones)]
merged

,gameId,homeMarket,awayMarket,secsIntoGame,teamMarket,actionType,subType,success,side,shotDist,zones6,zones13,season,team,Year,conf,similar_team,half,primary_side,side_mismatch,arena_School,arena_Conference,arena_Wall Number,arena_Side,arena_Distance,arena_Type of Wall,arena_Arena,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type
0,2549421,East Texas A&M,Nicholls,52.0,Nicholls,2pt,stepbackjumpshot,True,LEFT,15.719,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
1,2549421,East Texas A&M,Nicholls,122.0,Nicholls,3pt,jumpshot,False,LEFT,25.014,atb3,rw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
2,2549421,East Texas A&M,Nicholls,391.0,Nicholls,2pt,pullupjumpshot,True,LEFT,11.751,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
3,2549421,East Texas A&M,Nicholls,506.0,Nicholls,3pt,jumpshot,False,LEFT,28.561,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
5,2549421,East Texas A&M,Nicholls,1312.0,Nicholls,3pt,jumpshot,False,RIGHT,26.062,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,2,RIGHT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90813,2194141,UC San Diego,CSU Bakersfield,2472.0,CSU Bakersfield,3pt,jumpshot,False,LEFT,23.738,atb3,rw3,2023,UC San Diego,2023,BW,CSUN,3,LEFT,False,UC San Diego,Big West,1.0,Right,Close,Whole,LionTree Arena,False,True,NaN,Close,NaN,Whole
90815,2531544,UC Irvine,Cal Poly,1150.6,Cal Poly,3pt,jumpshot,False,LEFT,25.633,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,1,LEFT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90816,2531544,UC Irvine,Cal Poly,1213.0,Cal Poly,3pt,jumpshot,False,RIGHT,23.435,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90817,2531544,UC Irvine,Cal Poly,1354.0,Cal Poly,3pt,jumpshot,True,RIGHT,26.160,atb3,tok3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90819,2531544,UC Irvine,Cal Poly,1482.0,Cal Poly,3pt,jumpshot,False,RIGHT,25.577,atb3,rw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN

In [196]:
zone_summary = (
    merged
    .groupby(["homeMarket", "arena_Arena", "season", "zones13","side","similar_team"])  # or use side/shotDist if not zoned yet
    .agg(
        attempts=("success", "count"),
        makes=("success", "sum")
    )
    .assign(FG_pct=lambda x: x["makes"] / x["attempts"])
    .reset_index()
)

In [197]:
zone_summary

,homeMarket,arena_Arena,season,zones13,side,similar_team,attempts,makes,FG_pct
0,Air Force,Clune Arena,2021,heave3,RIGHT,Wyoming,1,0,0.000000
1,Air Force,Clune Arena,2021,le2,LEFT,Wyoming,10,3,0.300000
2,Air Force,Clune Arena,2021,le2,RIGHT,Wyoming,11,4,0.363636
3,Air Force,Clune Arena,2021,lw3,LEFT,Wyoming,32,11,0.343750
4,Air Force,Clune Arena,2021,lw3,RIGHT,Wyoming,30,13,0.433333
...,...,...,...,...,...,...,...,...,...
1592,Yale,John J. Lee Amphitheater,2025,re2,RIGHT,Brown,4,0,0.000000
1593,Yale,John J. Lee Amphitheater,2025,rw3,LEFT,Brown,44,17,0.386364
1594,Yale,John J. Lee Amphitheater,2025,rw3,RIGHT,Brown,34,13,0.382353
1595,Yale,John J. Lee Amphitheater,2025,tok3,LEFT,Brown,31,4,0.129032
1596,Yale,John J. Lee Amphitheater,2025,tok3,RIGHT,Brown,36,12,0.333333

In [198]:
pd.set_option("display.max_columns", 40)

In [199]:
zone_summary = zone_summary.merge(
    merged[[
        "arena_Arena", "arena_Side", "arena_Distance", "arena_Type of Wall",
        "arena_Left_Wall", "arena_Right_Wall", 
        "arena_Left_Wall_Distance", "arena_Right_Wall_Distance",
        "arena_Left_Wall_Type", "arena_Right_Wall_Type"
    ]].drop_duplicates(),
    on="arena_Arena",
    how="left"
)

In [200]:
similar_lookup = (
    zone_summary
    .groupby(["homeMarket", "season", "zones13", "side"], as_index=False)
    .agg(
        sim_attempts=("attempts", "sum"),
        sim_makes=("makes", "sum")
    )
    .assign(FG_pct_similar=lambda d: d["sim_makes"] / d["sim_attempts"])
    .rename(columns={"homeMarket": "sim_team"})
    [["sim_team", "season", "zones13", "side", "FG_pct_similar", "sim_attempts"]]
)

In [201]:
similar_lookup

       sim_team  season zones13   side  FG_pct_similar  sim_attempts
0     Air Force    2021  heave3  RIGHT        0.000000             1
1     Air Force    2021     le2   LEFT        0.300000            10
2     Air Force    2021     le2  RIGHT        0.363636            11
3     Air Force    2021     lw3   LEFT        0.343750            32
4     Air Force    2021     lw3  RIGHT        0.433333            30
...         ...     ...     ...    ...             ...           ...
1592       Yale    2025     re2  RIGHT        0.000000             4
1593       Yale    2025     rw3   LEFT        0.386364            44
1594       Yale    2025     rw3  RIGHT        0.382353            34
1595       Yale    2025    tok3   LEFT        0.129032            31
1596       Yale    2025    tok3  RIGHT        0.333333            36

[1597 rows x 6 columns]

In [202]:
zone_summary

,homeMarket,arena_Arena,season,zones13,side,similar_team,attempts,makes,FG_pct,arena_Side,arena_Distance,arena_Type of Wall,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type
0,Air Force,Clune Arena,2021,heave3,RIGHT,Wyoming,1,0,0.000000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
1,Air Force,Clune Arena,2021,le2,LEFT,Wyoming,10,3,0.300000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
2,Air Force,Clune Arena,2021,le2,RIGHT,Wyoming,11,4,0.363636,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
3,Air Force,Clune Arena,2021,lw3,LEFT,Wyoming,32,11,0.343750,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
4,Air Force,Clune Arena,2021,lw3,RIGHT,Wyoming,30,13,0.433333,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,Yale,John J. Lee Amphitheater,2025,re2,RIGHT,Brown,4,0,0.000000,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1593,Yale,John J. Lee Amphitheater,2025,rw3,LEFT,Brown,44,17,0.386364,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1594,Yale,John J. Lee Amphitheater,2025,rw3,RIGHT,Brown,34,13,0.382353,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1595,Yale,John J. Lee Amphitheater,2025,tok3,LEFT,Brown,31,4,0.129032,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1596,Yale,John J. Lee Amphitheater,2025,tok3,RIGHT,Brown,36,12,0.333333,Both,Far,Mix,True,True,Far,Far,Mix,Mix

In [203]:
merged

,gameId,homeMarket,awayMarket,secsIntoGame,teamMarket,actionType,subType,success,side,shotDist,zones6,zones13,season,team,Year,conf,similar_team,half,primary_side,side_mismatch,arena_School,arena_Conference,arena_Wall Number,arena_Side,arena_Distance,arena_Type of Wall,arena_Arena,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type
0,2549421,East Texas A&M,Nicholls,52.0,Nicholls,2pt,stepbackjumpshot,True,LEFT,15.719,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
1,2549421,East Texas A&M,Nicholls,122.0,Nicholls,3pt,jumpshot,False,LEFT,25.014,atb3,rw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
2,2549421,East Texas A&M,Nicholls,391.0,Nicholls,2pt,pullupjumpshot,True,LEFT,11.751,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
3,2549421,East Texas A&M,Nicholls,506.0,Nicholls,3pt,jumpshot,False,LEFT,28.561,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
5,2549421,East Texas A&M,Nicholls,1312.0,Nicholls,3pt,jumpshot,False,RIGHT,26.062,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,2,RIGHT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90813,2194141,UC San Diego,CSU Bakersfield,2472.0,CSU Bakersfield,3pt,jumpshot,False,LEFT,23.738,atb3,rw3,2023,UC San Diego,2023,BW,CSUN,3,LEFT,False,UC San Diego,Big West,1.0,Right,Close,Whole,LionTree Arena,False,True,NaN,Close,NaN,Whole
90815,2531544,UC Irvine,Cal Poly,1150.6,Cal Poly,3pt,jumpshot,False,LEFT,25.633,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,1,LEFT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90816,2531544,UC Irvine,Cal Poly,1213.0,Cal Poly,3pt,jumpshot,False,RIGHT,23.435,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90817,2531544,UC Irvine,Cal Poly,1354.0,Cal Poly,3pt,jumpshot,True,RIGHT,26.160,atb3,tok3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90819,2531544,UC Irvine,Cal Poly,1482.0,Cal Poly,3pt,jumpshot,False,RIGHT,25.577,atb3,rw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN

In [204]:
zone_summary

,homeMarket,arena_Arena,season,zones13,side,similar_team,attempts,makes,FG_pct,arena_Side,arena_Distance,arena_Type of Wall,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type
0,Air Force,Clune Arena,2021,heave3,RIGHT,Wyoming,1,0,0.000000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
1,Air Force,Clune Arena,2021,le2,LEFT,Wyoming,10,3,0.300000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
2,Air Force,Clune Arena,2021,le2,RIGHT,Wyoming,11,4,0.363636,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
3,Air Force,Clune Arena,2021,lw3,LEFT,Wyoming,32,11,0.343750,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
4,Air Force,Clune Arena,2021,lw3,RIGHT,Wyoming,30,13,0.433333,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,Yale,John J. Lee Amphitheater,2025,re2,RIGHT,Brown,4,0,0.000000,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1593,Yale,John J. Lee Amphitheater,2025,rw3,LEFT,Brown,44,17,0.386364,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1594,Yale,John J. Lee Amphitheater,2025,rw3,RIGHT,Brown,34,13,0.382353,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1595,Yale,John J. Lee Amphitheater,2025,tok3,LEFT,Brown,31,4,0.129032,Both,Far,Mix,True,True,Far,Far,Mix,Mix
1596,Yale,John J. Lee Amphitheater,2025,tok3,RIGHT,Brown,36,12,0.333333,Both,Far,Mix,True,True,Far,Far,Mix,Mix

In [205]:
zone_with_similar = (
    zone_summary
    .merge(
        similar_lookup,
        left_on=["similar_team", "season", "zones13", "side"],
        right_on=["sim_team",     "season", "zones13", "side"],
        how="left",
        validate="m:1"
    )
)

In [206]:
zone_with_similar["diff_FG_pct"] = (
    zone_with_similar["FG_pct"] - zone_with_similar["FG_pct_similar"]
)

In [207]:
zone_with_similar

,homeMarket,arena_Arena,season,zones13,side,similar_team,attempts,makes,FG_pct,arena_Side,arena_Distance,arena_Type of Wall,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type,sim_team,FG_pct_similar,sim_attempts,diff_FG_pct
0,Air Force,Clune Arena,2021,heave3,RIGHT,Wyoming,1,0,0.000000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.000000,1.0,0.000000
1,Air Force,Clune Arena,2021,le2,LEFT,Wyoming,10,3,0.300000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.384615,13.0,-0.084615
2,Air Force,Clune Arena,2021,le2,RIGHT,Wyoming,11,4,0.363636,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.571429,14.0,-0.207792
3,Air Force,Clune Arena,2021,lw3,LEFT,Wyoming,32,11,0.343750,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.444444,18.0,-0.100694
4,Air Force,Clune Arena,2021,lw3,RIGHT,Wyoming,30,13,0.433333,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.222222,18.0,0.211111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,Yale,John J. Lee Amphitheater,2025,re2,RIGHT,Brown,4,0,0.000000,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.375000,8.0,-0.375000
1593,Yale,John J. Lee Amphitheater,2025,rw3,LEFT,Brown,44,17,0.386364,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.260870,23.0,0.125494
1594,Yale,John J. Lee Amphitheater,2025,rw3,RIGHT,Brown,34,13,0.382353,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.466667,15.0,-0.084314
1595,Yale,John J. Lee Amphitheater,2025,tok3,LEFT,Brown,31,4,0.129032,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.285714,21.0,-0.156682
1596,Yale,John J. Lee Amphitheater,2025,tok3,RIGHT,Brown,36,12,0.333333,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.241379,29.0,0.091954

In [208]:
zone_with_similar[zone_with_similar["homeMarket"] == "UC San Diego"]

,homeMarket,arena_Arena,season,zones13,side,similar_team,attempts,makes,FG_pct,arena_Side,arena_Distance,arena_Type of Wall,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type,sim_team,FG_pct_similar,sim_attempts,diff_FG_pct
1368,UC San Diego,LionTree Arena,2021,heave3,LEFT,CSUN,3,1,0.333333,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1369,UC San Diego,LionTree Arena,2021,heave3,RIGHT,CSUN,2,1,0.500000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1370,UC San Diego,LionTree Arena,2021,le2,LEFT,CSUN,4,1,0.250000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1371,UC San Diego,LionTree Arena,2021,le2,RIGHT,CSUN,8,3,0.375000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1372,UC San Diego,LionTree Arena,2021,lw3,LEFT,CSUN,18,8,0.444444,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1373,UC San Diego,LionTree Arena,2021,lw3,RIGHT,CSUN,17,7,0.411765,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1374,UC San Diego,LionTree Arena,2021,re2,LEFT,CSUN,2,2,1.000000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1375,UC San Diego,LionTree Arena,2021,re2,RIGHT,CSUN,10,5,0.500000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1376,UC San Diego,LionTree Arena,2021,rw3,LEFT,CSUN,21,7,0.333333,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1377,UC San Diego,LionTree Arena,2021,rw3,RIGHT,CSUN,22,7,0.318182,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1378,UC San Diego,LionTree Arena,2021,tok3,LEFT,CSUN,17,5,0.294118,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1379,UC San Diego,LionTree Arena,2021,tok3,RIGHT,CSUN,23,10,0.434783,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1380,UC San Diego,LionTree Arena,2022,heave3,LEFT,CSUN,2,0,0.000000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1381,UC San Diego,LionTree Arena,2022,heave3,RIGHT,CSUN,5,1,0.200000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1382,UC San Diego,LionTree Arena,2022,le2,LEFT,CSUN,10,5,0.500000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1383,UC San Diego,LionTree Arena,2022,le2,RIGHT,CSUN,10,6,0.600000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1384,UC San Diego,LionTree Arena,2022,lw3,LEFT,CSUN,36,15,0.416667,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1385,UC San Diego,LionTree Arena,2022,lw3,RIGHT,CSUN,31,6,0.193548,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1386,UC San Diego,LionTree Arena,2022,re2,LEFT,CSUN,12,4,0.333333,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1387,UC San Diego,LionTree Arena,2022,re2,RIGHT,CSUN,18,7,0.388889,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1388,UC San Diego,LionTree Arena,2022,rw3,LEFT,CSUN,21,5,0.238095,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1389,UC San Diego,LionTree Arena,2022,rw3,RIGHT,CSUN,17,6,0.352941,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1390,UC San Diego,LionTree Arena,2022,tok3,LEFT,CSUN,18,5,0.277778,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1391,UC San Diego,LionTree Arena,2022,tok3,RIGHT,CSUN,20,9,0.450000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1392,UC San Diego,LionTree Arena,2023,heave3,LEFT,CSUN,1,0,0.000000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1393,UC San Diego,LionTree Arena,2023,heave3,RIGHT,CSUN,1,0,0.000000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1394,UC San Diego,LionTree Arena,2023,le2,LEFT,CSUN,7,3,0.428571,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1395,UC San Diego,LionTree Arena,2023,le2,RIGHT,CSUN,10,5,0.500000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1396,UC San Diego,LionTree Arena,2023,lw3,LEFT,CSUN,13,9,0.692308,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1397,UC San Diego,LionTree Arena,2023,lw3,RIGHT,CSUN,35,12,0.342857,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1398,UC San Diego,LionTree Arena,2023,re2,LEFT,CSUN,8,2,0.250000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1399,UC San Diego,LionTree Arena,2023,re2,RIGHT,CSUN,12,6,0.500000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1400,UC San Diego,LionTree Arena,2023,rw3,LEFT,CSUN,24,13,0.541667,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1401,UC San Diego,LionTree Arena,2023,rw3,RIGHT,CSUN,26,9,0.346154,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1402,UC San Diego,LionTree Arena,2023,tok3,LEFT,CSUN,20,7,0.350000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1403,UC San Diego,LionTree Arena,2023,tok3,RIGHT,CSUN,22,5,0.227273,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1404,UC San Diego,LionTree Arena,2024,heave3,LEFT,Long Beach St.,1,0,0.000000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1405,UC San Diego,LionTree Arena,2024,le2,LEFT,Long Beach St.,17,10,0.588235,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1406,UC San Diego,LionTree Arena,2024,le2,RIGHT,Long Beach St.,25,14,0.560000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1407,UC San Diego,LionTree Arena,2024,lw3,LEFT,Long Beach St.,26,8,0.307692,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1408,UC San Diego,LionTree Arena,2024,lw3,RIGHT,Long Beach St.,33,9,0.272727,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1409,UC San Diego,LionTree Arena,2024,re2,LEFT,Long Beach St.,10,2,0.200000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1410,UC San Diego,LionTree Arena,2024,re2,RIGHT,Long Beach St.,25,4,0.160000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1411,UC San Diego,LionTree Arena,2024,rw3,LEFT,Long Beach St.,29,12,0.413793,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1412,UC San Diego,LionTree Arena,2024,rw3,RIGHT,Long Beach St.,29,13,0.448276,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1413,UC San Diego,LionTree Arena,2024,tok3,LEFT,Long Beach St.,36,11,0.305556,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1414,UC San Diego,LionTree Arena,2024,tok3,RIGHT,Long Beach St.,26,4,0.153846,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,NaN,NaN,NaN,NaN
1415,UC San Diego,LionTree Arena,2025,heave3,LEFT,UC Irvine,1,0,0.000000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.400000,5.0,-0.400000
1416,UC San Diego,LionTree Arena,2025,heave3,RIGHT,UC Irvine,6,0,0.000000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.500000,4.0,-0.500000
1417,UC San Diego,LionTree Arena,2025,le2,LEFT,UC Irvine,13,7,0.538462,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.421053,19.0,0.117409
1418,UC San Diego,LionTree Arena,2025,le2,RIGHT,UC Irvine,11,2,0.181818,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.214286,14.0,-0.032468
1419,UC San Diego,LionTree Arena,2025,lw3,LEFT,UC Irvine,41,7,0.170732,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.425532,47.0,-0.254800
1420,UC San Diego,LionTree Arena,2025,lw3,RIGHT,UC Irvine,32,12,0.375000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.468750,32.0,-0.093750
1421,UC San Diego,LionTree Arena,2025,re2,LEFT,UC Irvine,4,2,0.500000,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.454545,11.0,0.045455
1422,UC San Diego,LionTree Arena,2025,re2,RIGHT,UC Irvine,6,1,0.166667,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.375000,8.0,-0.208333
1423,UC San Diego,LionTree Arena,2025,rw3,LEFT,UC Irvine,30,7,0.233333,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.428571,21.0,-0.195238
1424,UC San Diego,LionTree Arena,2025,rw3,RIGHT,UC Irvine,38,9,0.236842,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.178571,28.0,0.058271
1425,UC San Diego,LionTree Arena,2025,tok3,LEFT,UC Irvine,41,15,0.365854,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.342857,35.0,0.022997
1426,UC San Diego,LionTree Arena,2025,tok3,RIGHT,UC Irvine,42,15,0.357143,Right,Close,Whole,False,True,NaN,Close,NaN,Whole,UC Irvine,0.375000,40.0,-0.017857

In [209]:
by_type

,zones13,side_wall_type,focal_attempts,focal_makes,focal_FG_pct,sim_attempts,sim_makes,sim_FG_pct,w_mean_diff
0,atr2,Mix,310.0,142.0,0.458065,232.0,106.0,0.456897,-0.036151
1,atr2,None,2098.0,860.0,0.409914,1814.0,773.0,0.426130,0.004485
2,atr2,Whole,336.0,150.0,0.446429,387.0,168.0,0.434109,0.049820
3,heave3,Mix,54.0,13.0,0.240741,25.0,4.0,0.160000,0.055556
4,heave3,None,355.0,68.0,0.191549,226.0,40.0,0.176991,0.006606
5,heave3,Whole,53.0,13.0,0.245283,30.0,12.0,0.400000,-0.257862
6,lb2,Mix,514.0,190.0,0.369650,483.0,190.0,0.393375,-0.018442
7,lb2,None,3276.0,1106.0,0.337607,3302.0,1141.0,0.345548,-0.020723
8,lb2,Whole,491.0,197.0,0.401222,486.0,170.0,0.349794,0.029172
9,lc3,Mix,704.0,251.0,0.356534,661.0,227.0,0.343419,0.020184
10,lc3,None,5108.0,1822.0,0.356695,5120.0,1850.0,0.361328,-0.020529
11,lc3,Whole,701.0,243.0,0.346648,766.0,270.0,0.352480,-0.044540
12,le2,Mix,631.0,232.0,0.367670,547.0,205.0,0.374771,-0.007510
13,le2,None,4262.0,1560.0,0.366025,4209.0,1550.0,0.368258,-0.004713
14,le2,Whole,602.0,227.0,0.377076,600.0,231.0,0.385000,-0.009917
15,lw3,Mix,1744.0,602.0,0.345183,1651.0,573.0,0.347062,-0.003400
16,lw3,None,11474.0,3806.0,0.331706,11487.0,3816.0,0.332202,-0.001873
17,lw3,Whole,1830.0,619.0,0.338251,1768.0,587.0,0.332014,0.004731
18,paint2,Mix,1533.0,620.0,0.404436,1627.0,658.0,0.404425,-0.011691
19,paint2,None,11567.0,4571.0,0.395176,11278.0,4486.0,0.397766,-0.004913
20,paint2,Whole,1755.0,737.0,0.419943,1541.0,633.0,0.410772,0.011390
21,rb2,Mix,483.0,162.0,0.335404,567.0,210.0,0.370370,-0.037964
22,rb2,None,3599.0,1265.0,0.351487,3721.0,1329.0,0.357162,-0.011353
23,rb2,Whole,614.0,234.0,0.381107,507.0,187.0,0.368836,0.009234
24,rc3,Mix,585.0,206.0,0.352137,598.0,213.0,0.356187,-0.013466
25,rc3,None,4367.0,1533.0,0.351042,4338.0,1482.0,0.341632,0.014090
26,rc3,Whole,610.0,217.0,0.355738,693.0,251.0,0.362193,-0.013451
27,re2,Mix,558.0,222.0,0.397849,519.0,171.0,0.329480,0.068796
28,re2,None,4109.0,1507.0,0.366756,3991.0,1460.0,0.365823,0.001846
29,re2,Whole,634.0,218.0,0.343849,563.0,213.0,0.378330,-0.052238
30,rw3,Mix,1421.0,491.0,0.345531,1416.0,476.0,0.336158,0.011548
31,rw3,None,9791.0,3334.0,0.340517,9893.0,3399.0,0.343576,-0.003567
32,rw3,Whole,1492.0,478.0,0.320375,1506.0,533.0,0.353918,-0.038953
33,tok3,Mix,1556.0,529.0,0.339974,1519.0,520.0,0.342330,0.006771
34,tok3,None,10043.0,3299.0,0.328488,9824.0,3217.0,0.327463,-0.000009
35,tok3,Whole,1561.0,528.0,0.338245,1504.0,483.0,0.321144,0.013403

In [210]:
merged

,gameId,homeMarket,awayMarket,secsIntoGame,teamMarket,actionType,subType,success,side,shotDist,zones6,zones13,season,team,Year,conf,similar_team,half,primary_side,side_mismatch,arena_School,arena_Conference,arena_Wall Number,arena_Side,arena_Distance,arena_Type of Wall,arena_Arena,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type
0,2549421,East Texas A&M,Nicholls,52.0,Nicholls,2pt,stepbackjumpshot,True,LEFT,15.719,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
1,2549421,East Texas A&M,Nicholls,122.0,Nicholls,3pt,jumpshot,False,LEFT,25.014,atb3,rw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
2,2549421,East Texas A&M,Nicholls,391.0,Nicholls,2pt,pullupjumpshot,True,LEFT,11.751,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
3,2549421,East Texas A&M,Nicholls,506.0,Nicholls,3pt,jumpshot,False,LEFT,28.561,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,1,LEFT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
5,2549421,East Texas A&M,Nicholls,1312.0,Nicholls,3pt,jumpshot,False,RIGHT,26.062,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,2,RIGHT,False,East Texas A&M,Southland,2.0,Both,Mix,Mix,The Field House,True,True,Close,Far,Whole,Mix
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90813,2194141,UC San Diego,CSU Bakersfield,2472.0,CSU Bakersfield,3pt,jumpshot,False,LEFT,23.738,atb3,rw3,2023,UC San Diego,2023,BW,CSUN,3,LEFT,False,UC San Diego,Big West,1.0,Right,Close,Whole,LionTree Arena,False,True,NaN,Close,NaN,Whole
90815,2531544,UC Irvine,Cal Poly,1150.6,Cal Poly,3pt,jumpshot,False,LEFT,25.633,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,1,LEFT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90816,2531544,UC Irvine,Cal Poly,1213.0,Cal Poly,3pt,jumpshot,False,RIGHT,23.435,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90817,2531544,UC Irvine,Cal Poly,1354.0,Cal Poly,3pt,jumpshot,True,RIGHT,26.160,atb3,tok3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN
90819,2531544,UC Irvine,Cal Poly,1482.0,Cal Poly,3pt,jumpshot,False,RIGHT,25.577,atb3,rw3,2025,UC Irvine,2025,BW,UC San Diego,2,RIGHT,False,UC Irvine,Big West,1.0,Left,Far,Mix,Bren Events Center,True,False,Far,NaN,Mix,NaN

In [211]:
import numpy as np

# Does the shot’s basket have a wall?
merged["side_has_wall"] = np.where(
    merged["side"].eq("LEFT"),  merged["arena_Left_Wall"],
    np.where(merged["side"].eq("RIGHT"), merged["arena_Right_Wall"], np.nan)
)

# Distance for that basket (Close/Far/None)
merged["side_wall_distance"] = np.where(
    merged["side"].eq("LEFT"),  merged["arena_Left_Wall_Distance"],
    np.where(merged["side"].eq("RIGHT"), merged["arena_Right_Wall_Distance"], np.nan)
)
merged["side_wall_distance"] = np.where(
    merged["side_has_wall"] == True, merged["side_wall_distance"], "None"
)

# (Optional) Type for that basket (Whole/Mix/None)
merged["side_wall_type"] = np.where(
    merged["side"].eq("LEFT"),  merged["arena_Left_Wall_Type"],
    np.where(merged["side"].eq("RIGHT"), merged["arena_Right_Wall_Type"], np.nan)
)
merged["side_wall_type"] = np.where(
    merged["side_has_wall"] == True, merged["side_wall_type"], "None"
)

/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/2904015711.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged["side_has_wall"] = np.where(
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/2904015711.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged["side_wall_distance"] = np.where(
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/2904015711.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged["side_wall_distance"] = np.where(
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/2904015711.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged["side_wall_type"] = np.where(
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/2904015711.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged["side_wall_type"] = np.where(

In [212]:
zone_summary = (
    merged
    .groupby(
        ["homeMarket","season","zones13","side","similar_team",
         "side_wall_distance","side_wall_type"],
        dropna=False
    )
    .agg(attempts=("success","count"), makes=("success","sum"))
    .assign(FG_pct=lambda d: d["makes"]/d["attempts"])
    .reset_index()
)

similar_lookup = (
    zone_summary
    .groupby(["homeMarket","season","zones13","side"], as_index=False)
    .agg(sim_attempts=("attempts","sum"), sim_makes=("makes","sum"))
    .assign(FG_pct_similar=lambda d: d["sim_makes"]/d["sim_attempts"])
    .rename(columns={"homeMarket":"sim_team"})
    [["sim_team","season","zones13","side","FG_pct_similar","sim_attempts"]]
)

zone_with_similar = (
    zone_summary
    .merge(
        similar_lookup,
        left_on=["similar_team","season","zones13","side"],
        right_on=["sim_team","season","zones13","side"],
        how="left",
        validate="m:1"
    )
)
zone_with_similar["diff_FG_pct"] = zone_with_similar["FG_pct"] - zone_with_similar["FG_pct_similar"]



by_distance = (
    zone_with_similar
    .groupby(["zones13","side_wall_distance"], dropna=False)
    .apply(lambda g: pd.Series({
        "focal_attempts": g["attempts"].sum(),
        "focal_makes": g["makes"].sum(),
        "focal_FG_pct": g["makes"].sum() / g["attempts"].sum() if g["attempts"].sum() else np.nan,
        "sim_attempts": g["sim_attempts"].sum(),
        "sim_makes": (g["FG_pct_similar"] * g["sim_attempts"]).sum(),
        "sim_FG_pct": (g["FG_pct_similar"] * g["sim_attempts"]).sum() / g["sim_attempts"].sum() if g["sim_attempts"].sum() else np.nan,
        "w_mean_diff": (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum()
    }))
    .reset_index()
)

by_distance_no_zone = (
    zone_with_similar
    .groupby(["side_wall_distance"], dropna=False)
    .apply(lambda g: pd.Series({
        "focal_attempts": g["attempts"].sum(),
        "focal_makes": g["makes"].sum(),
        "focal_FG_pct": g["makes"].sum() / g["attempts"].sum() if g["attempts"].sum() else np.nan,
        "sim_attempts": g["sim_attempts"].sum(),
        "sim_makes": (g["FG_pct_similar"] * g["sim_attempts"]).sum(),
        "sim_FG_pct": (g["FG_pct_similar"] * g["sim_attempts"]).sum() / g["sim_attempts"].sum() if g["sim_attempts"].sum() else np.nan,
        "w_mean_diff": (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum()
    }))
    .reset_index()
)

by_type = (
    zone_with_similar
    .groupby(["zones13","side_wall_type"], dropna=False)
    .apply(lambda g: pd.Series({
        "focal_attempts": g["attempts"].sum(),
        "focal_makes": g["makes"].sum(),
        "focal_FG_pct": g["makes"].sum() / g["attempts"].sum() if g["attempts"].sum() else np.nan,
        "sim_attempts": g["sim_attempts"].sum(),
        "sim_makes": (g["FG_pct_similar"] * g["sim_attempts"]).sum(),
        "sim_FG_pct": (g["FG_pct_similar"] * g["sim_attempts"]).sum() / g["sim_attempts"].sum() if g["sim_attempts"].sum() else np.nan,
        "w_mean_diff": (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum()
    }))
    .reset_index()
)

by_type_no_zone = (
    zone_with_similar
    .groupby(["side_wall_type"], dropna=False)
    .apply(lambda g: pd.Series({
        "focal_attempts": g["attempts"].sum(),
        "focal_makes": g["makes"].sum(),
        "focal_FG_pct": g["makes"].sum() / g["attempts"].sum() if g["attempts"].sum() else np.nan,
        "sim_attempts": g["sim_attempts"].sum(),
        "sim_makes": (g["FG_pct_similar"] * g["sim_attempts"]).sum(),
        "sim_FG_pct": (g["FG_pct_similar"] * g["sim_attempts"]).sum() / g["sim_attempts"].sum() if g["sim_attempts"].sum() else np.nan,
        "w_mean_diff": (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum()
    }))
    .reset_index()
)

/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/489384824.py:39: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/489384824.py:54: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/489384824.py:69: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/489384824.py:84: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: pd.Series({

In [213]:
zone_with_similar

,homeMarket,season,zones13,side,similar_team,side_wall_distance,side_wall_type,attempts,makes,FG_pct,sim_team,FG_pct_similar,sim_attempts,diff_FG_pct
0,A&M-Corpus Christi,2021,le2,LEFT,New Orleans,None,None,7,3,0.428571,New Orleans,0.555556,9.0,-0.126984
1,A&M-Corpus Christi,2021,le2,RIGHT,New Orleans,None,None,9,2,0.222222,New Orleans,0.142857,7.0,0.079365
2,A&M-Corpus Christi,2021,lw3,LEFT,New Orleans,None,None,11,4,0.363636,New Orleans,0.384615,13.0,-0.020979
3,A&M-Corpus Christi,2021,lw3,RIGHT,New Orleans,None,None,15,7,0.466667,New Orleans,0.421053,19.0,0.045614
4,A&M-Corpus Christi,2021,re2,LEFT,New Orleans,None,None,9,1,0.111111,New Orleans,0.461538,13.0,-0.350427
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2696,Yale,2025,re2,RIGHT,Brown,Far,Mix,4,0,0.000000,Brown,0.375000,8.0,-0.375000
2697,Yale,2025,rw3,LEFT,Brown,Far,Mix,44,17,0.386364,Brown,0.260870,23.0,0.125494
2698,Yale,2025,rw3,RIGHT,Brown,Far,Mix,34,13,0.382353,Brown,0.466667,15.0,-0.084314
2699,Yale,2025,tok3,LEFT,Brown,Far,Mix,31,4,0.129032,Brown,0.285714,21.0,-0.156682
2700,Yale,2025,tok3,RIGHT,Brown,Far,Mix,36,12,0.333333,Brown,0.241379,29.0,0.091954

In [214]:
by_distance_no_zone

,side_wall_distance,focal_attempts,focal_makes,focal_FG_pct,sim_attempts,sim_makes,sim_FG_pct,w_mean_diff
0,Close,6680.0,2349.0,0.351647,6415.0,2268.0,0.353546,-0.005973
1,Far,5456.0,1823.0,0.334128,5233.0,1740.0,0.332505,0.002981
2,None,40034.0,13574.0,0.339062,39630.0,13482.0,0.340197,-0.001665

In [215]:
by_distance

,zones13,side_wall_distance,focal_attempts,focal_makes,focal_FG_pct,sim_attempts,sim_makes,sim_FG_pct,w_mean_diff
0,heave3,Close,61.0,14.0,0.229508,25.0,10.0,0.400000,-0.234973
1,heave3,Far,46.0,12.0,0.260870,30.0,6.0,0.200000,0.079710
2,heave3,None,355.0,68.0,0.191549,226.0,40.0,0.176991,0.006606
3,le2,Close,604.0,239.0,0.395695,620.0,259.0,0.417742,-0.024677
4,le2,Far,629.0,220.0,0.349762,527.0,177.0,0.335863,0.006671
5,le2,None,4262.0,1560.0,0.366025,4209.0,1550.0,0.368258,-0.004713
6,lw3,Close,2030.0,728.0,0.358621,1906.0,666.0,0.349423,0.009106
7,lw3,Far,1544.0,493.0,0.319301,1513.0,494.0,0.326504,-0.010206
8,lw3,None,11474.0,3806.0,0.331706,11487.0,3816.0,0.332202,-0.001873
9,re2,Close,664.0,231.0,0.347892,579.0,212.0,0.366149,-0.030577
10,re2,Far,528.0,209.0,0.395833,503.0,172.0,0.341948,0.048432
11,re2,None,4109.0,1507.0,0.366756,3991.0,1460.0,0.365823,0.001846
12,rw3,Close,1577.0,532.0,0.337349,1579.0,560.0,0.354655,-0.020146
13,rw3,Far,1336.0,437.0,0.327096,1343.0,449.0,0.334326,-0.007440
14,rw3,None,9791.0,3334.0,0.340517,9893.0,3399.0,0.343576,-0.003567
15,tok3,Close,1744.0,605.0,0.346904,1706.0,561.0,0.328839,0.013147
16,tok3,Far,1373.0,452.0,0.329206,1317.0,442.0,0.335611,0.006212
17,tok3,None,10043.0,3299.0,0.328488,9824.0,3217.0,0.327463,-0.000009

In [216]:
by_type

,zones13,side_wall_type,focal_attempts,focal_makes,focal_FG_pct,sim_attempts,sim_makes,sim_FG_pct,w_mean_diff
0,heave3,Mix,54.0,13.0,0.240741,25.0,4.0,0.160000,0.055556
1,heave3,None,355.0,68.0,0.191549,226.0,40.0,0.176991,0.006606
2,heave3,Whole,53.0,13.0,0.245283,30.0,12.0,0.400000,-0.257862
3,le2,Mix,631.0,232.0,0.367670,547.0,205.0,0.374771,-0.007510
4,le2,None,4262.0,1560.0,0.366025,4209.0,1550.0,0.368258,-0.004713
5,le2,Whole,602.0,227.0,0.377076,600.0,231.0,0.385000,-0.009917
6,lw3,Mix,1744.0,602.0,0.345183,1651.0,573.0,0.347062,-0.003400
7,lw3,None,11474.0,3806.0,0.331706,11487.0,3816.0,0.332202,-0.001873
8,lw3,Whole,1830.0,619.0,0.338251,1768.0,587.0,0.332014,0.004731
9,re2,Mix,558.0,222.0,0.397849,519.0,171.0,0.329480,0.068796
10,re2,None,4109.0,1507.0,0.366756,3991.0,1460.0,0.365823,0.001846
11,re2,Whole,634.0,218.0,0.343849,563.0,213.0,0.378330,-0.052238
12,rw3,Mix,1421.0,491.0,0.345531,1416.0,476.0,0.336158,0.011548
13,rw3,None,9791.0,3334.0,0.340517,9893.0,3399.0,0.343576,-0.003567
14,rw3,Whole,1492.0,478.0,0.320375,1506.0,533.0,0.353918,-0.038953
15,tok3,Mix,1556.0,529.0,0.339974,1519.0,520.0,0.342330,0.006771
16,tok3,None,10043.0,3299.0,0.328488,9824.0,3217.0,0.327463,-0.000009
17,tok3,Whole,1561.0,528.0,0.338245,1504.0,483.0,0.321144,0.013403

In [217]:
by_type_no_zone

,side_wall_type,focal_attempts,focal_makes,focal_FG_pct,sim_attempts,sim_makes,sim_FG_pct,w_mean_diff
0,Mix,5964.0,2089.0,0.350268,5677.0,1949.0,0.343315,0.009669
1,None,40034.0,13574.0,0.339062,39630.0,13482.0,0.340197,-0.001665
2,Whole,6172.0,2083.0,0.337492,5971.0,2059.0,0.344833,-0.013171

In [218]:
def classify_group(g):
    # Rank distances in this zone (higher w_mean_diff = better)
    ranks = g["w_mean_diff"].rank(method="min", ascending=False)

    g = g.copy()
    g["category"] = "Middle"
    g.loc[ranks == 1, "category"] = "Best"
    g.loc[ranks == ranks.max(), "category"] = "Worst"
    return g

# Apply classification per zone
ranked_distance = by_distance.groupby("zones13", group_keys=False).apply(classify_group)

# Count across zones
summary_counts_distance = (
    ranked_distance.groupby(["side_wall_distance","category"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

ranked_type = by_type.groupby("zones13", group_keys=False).apply(classify_group)

# Count across zones
summary_counts_type = (
    ranked_type.groupby(["side_wall_type","category"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/3593637350.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ranked_distance = by_distance.groupby("zones13", group_keys=False).apply(classify_group)
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/3593637350.py:22: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  ranked_type = by_type.groupby("zones13", group_keys=False).apply(classify_group)

In [219]:
summary_counts_distance

category side_wall_distance  Best  Middle  Worst
0                     Close     2       0      4
1                       Far     3       2      1
2                      None     1       4      1

In [220]:
summary_counts_type

category side_wall_type  Best  Middle  Worst
0                   Mix     3       2      1
1                  None     1       4      1
2                 Whole     2       0      4

In [224]:
ranked_type[(ranked_type["side_wall_type"]=="Whole") & (ranked_type["category"]=="Worst")]

,zones13,side_wall_type,focal_attempts,focal_makes,focal_FG_pct,sim_attempts,sim_makes,sim_FG_pct,w_mean_diff,category
2,heave3,Whole,53.0,13.0,0.245283,30.0,12.0,0.400000,-0.257862,Worst
5,le2,Whole,602.0,227.0,0.377076,600.0,231.0,0.385000,-0.009917,Worst
11,re2,Whole,634.0,218.0,0.343849,563.0,213.0,0.378330,-0.052238,Worst
14,rw3,Whole,1492.0,478.0,0.320375,1506.0,533.0,0.353918,-0.038953,Worst

In [186]:
ranked_distance

,zones13,side_wall_distance,focal_attempts,focal_makes,focal_FG_pct,sim_attempts,sim_makes,sim_FG_pct,w_mean_diff,category
0,atr2,Close,388.0,187.0,0.481959,378.0,171.0,0.452381,0.073924,Best
1,atr2,Far,258.0,105.0,0.406977,241.0,103.0,0.427386,-0.089728,Worst
2,atr2,None,2098.0,860.0,0.409914,1814.0,773.0,0.426130,0.004485,Middle
3,heave3,Close,61.0,14.0,0.229508,25.0,10.0,0.400000,-0.234973,Worst
4,heave3,Far,46.0,12.0,0.260870,30.0,6.0,0.200000,0.079710,Best
5,heave3,None,355.0,68.0,0.191549,226.0,40.0,0.176991,0.006606,Middle
6,lb2,Close,509.0,204.0,0.400786,512.0,192.0,0.375000,0.014375,Best
7,lb2,Far,496.0,183.0,0.368952,457.0,168.0,0.367615,-0.004985,Middle
8,lb2,None,3276.0,1106.0,0.337607,3302.0,1141.0,0.345548,-0.020723,Worst
9,lc3,Close,742.0,264.0,0.355795,753.0,260.0,0.345286,-0.026731,Worst
10,lc3,Far,663.0,230.0,0.346908,674.0,237.0,0.351632,0.004256,Best
11,lc3,None,5108.0,1822.0,0.356695,5120.0,1850.0,0.361328,-0.020529,Middle
12,le2,Close,604.0,239.0,0.395695,620.0,259.0,0.417742,-0.024677,Worst
13,le2,Far,629.0,220.0,0.349762,527.0,177.0,0.335863,0.006671,Best
14,le2,None,4262.0,1560.0,0.366025,4209.0,1550.0,0.368258,-0.004713,Middle
15,lw3,Close,2030.0,728.0,0.358621,1906.0,666.0,0.349423,0.009106,Best
16,lw3,Far,1544.0,493.0,0.319301,1513.0,494.0,0.326504,-0.010206,Worst
17,lw3,None,11474.0,3806.0,0.331706,11487.0,3816.0,0.332202,-0.001873,Middle
18,paint2,Close,1814.0,776.0,0.427784,1585.0,665.0,0.419558,0.011192,Best
19,paint2,Far,1474.0,581.0,0.394166,1583.0,626.0,0.395452,-0.012371,Worst
20,paint2,None,11567.0,4571.0,0.395176,11278.0,4486.0,0.397766,-0.004913,Middle
21,rb2,Close,597.0,227.0,0.380235,515.0,186.0,0.361165,0.023191,Best
22,rb2,Far,500.0,169.0,0.338000,559.0,211.0,0.377460,-0.053024,Worst
23,rb2,None,3599.0,1265.0,0.351487,3721.0,1329.0,0.357162,-0.011353,Middle
24,rc3,Close,639.0,217.0,0.339593,656.0,244.0,0.371951,-0.031710,Worst
25,rc3,Far,556.0,206.0,0.370504,635.0,220.0,0.346457,0.007519,Middle
26,rc3,None,4367.0,1533.0,0.351042,4338.0,1482.0,0.341632,0.014090,Best
27,re2,Close,664.0,231.0,0.347892,579.0,212.0,0.366149,-0.030577,Worst
28,re2,Far,528.0,209.0,0.395833,503.0,172.0,0.341948,0.048432,Best
29,re2,None,4109.0,1507.0,0.366756,3991.0,1460.0,0.365823,0.001846,Middle
30,rw3,Close,1577.0,532.0,0.337349,1579.0,560.0,0.354655,-0.020146,Worst
31,rw3,Far,1336.0,437.0,0.327096,1343.0,449.0,0.334326,-0.007440,Middle
32,rw3,None,9791.0,3334.0,0.340517,9893.0,3399.0,0.343576,-0.003567,Best
33,tok3,Close,1744.0,605.0,0.346904,1706.0,561.0,0.328839,0.013147,Best
34,tok3,Far,1373.0,452.0,0.329206,1317.0,442.0,0.335611,0.006212,Middle
35,tok3,None,10043.0,3299.0,0.328488,9824.0,3217.0,0.327463,-0.000009,Worst

In [ ]:
by_type = (
    zone_with_similar
    .groupby(["zones13", "arena_Type of Wall"], dropna=False)
    .apply(lambda g: pd.Series({
        # focal totals
        "focal_attempts": g["attempts"].sum(),
        "focal_makes": g["makes"].sum(),
        "focal_FG_pct": g["makes"].sum() / g["attempts"].sum() if g["attempts"].sum() > 0 else np.nan,

        # similar totals (reconstruct makes)
        "sim_attempts": g["sim_attempts"].sum(),
        "sim_makes": (g["FG_pct_similar"] * g["sim_attempts"]).sum(),
        "sim_FG_pct": (g["FG_pct_similar"] * g["sim_attempts"]).sum() / g["sim_attempts"].sum() if g["sim_attempts"].sum() > 0 else np.nan,

        # weighted mean ΔFG% (weights = focal attempts)
        "w_mean_diff": (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum()
    }))
    .reset_index()
)

by_type_no_zone = (
    zone_with_similar
    .groupby(["arena_Type of Wall"], dropna=False)
    .apply(lambda g: (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum())
    .reset_index(name="w_mean_diff")
)

In [131]:
zone_summary2 = (
    merged
    .groupby(["homeMarket","season","zones13","side","similar_team","side_wall_distance"], dropna=False)
    .agg(attempts=("success","count"), makes=("success","sum"))
    .assign(FG_pct=lambda d: d["makes"]/d["attempts"])
    .reset_index()
)
similar_lookup2 = (
    zone_summary2
    .groupby(["homeMarket","season","zones13","side"], as_index=False)
    .agg(sim_attempts=("attempts","sum"), sim_makes=("makes","sum"))
    .assign(FG_pct_similar=lambda d: d["sim_makes"]/d["sim_attempts"])
    .rename(columns={"homeMarket":"sim_team"})
    [["sim_team","season","zones13","side","FG_pct_similar","sim_attempts"]]
)
zone_with_similar2 = (
    zone_summary2
    .merge(
        similar_lookup,
        left_on=["similar_team","season","zones13","side"],
        right_on=["sim_team","season","zones13","side"],
        how="left",
        validate="m:1"
    )
)

zone_with_similar2["diff_FG_pct"] = zone_with_similar2["FG_pct"] - zone_with_similar2["FG_pct_similar"]

# Optional filters
zone_with_similar2 = zone_with_similar2.dropna(subset=["FG_pct_similar"])
zone_with_similar2 = zone_with_similar2.loc[
    (zone_with_similar2["attempts"] >= 10) & (zone_with_similar2["sim_attempts"] >= 10)
]

# Weighted mean ΔFG% by distance, per zone
by_distance = (
    zone_with_similar2
    .groupby(["zones13","side_wall_distance"], dropna=False)
    .apply(
        lambda g: pd.Series({
            # Total attempts and makes (from focal team)
            "total_attempts": g["attempts"].sum(),
            "total_makes": g["makes"].sum(),
            # Weighted mean ΔFG% (using attempts as weight)
            "w_mean_diff": (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum()
        })
    )
    .reset_index()
)
by_distance["focal_FG_pct"] = by_distance["total_makes"] / by_distance["total_attempts"]

by_distance_no_zone = (
    zone_with_similar2
    .groupby(["side_wall_distance"], dropna=False)
    .apply(
        lambda g: pd.Series({
            # Total attempts and makes (from focal team)
            "total_attempts": g["attempts"].sum(),
            "total_makes": g["makes"].sum(),
            # Weighted mean ΔFG% (using attempts as weight)
            "w_mean_diff": (g["diff_FG_pct"] * g["attempts"]).sum() / g["attempts"].sum()
        })
    )
    .reset_index()
)
by_distance_no_zone["focal_FG_pct"] = by_distance_no_zone["total_makes"] / by_distance_no_zone["total_attempts"]

/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/3494716584.py:39: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(
/var/folders/28/k_06cnf50jv837zrzkdd_xxc0000gn/T/ipykernel_79343/3494716584.py:55: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

In [132]:
by_distance_no_zone

  side_wall_distance  total_attempts  total_makes  w_mean_diff  focal_FG_pct
0              Close          6145.0       2298.0     0.005450      0.373963
1                Far          4392.0       1522.0    -0.003530      0.346539
2               None         30772.0      10890.0    -0.000941      0.353893

In [133]:
by_distance

,zones13,side_wall_distance,total_attempts,total_makes,w_mean_diff,focal_FG_pct
0,atr2,Close,29.0,16.0,0.244032,0.551724
1,atr2,None,66.0,22.0,-0.175363,0.333333
2,lb2,Close,102.0,47.0,0.083148,0.460784
3,lb2,Far,116.0,49.0,0.021332,0.422414
4,lb2,None,587.0,192.0,-0.048481,0.327087
5,lc3,Close,230.0,82.0,0.000661,0.356522
6,lc3,Far,191.0,67.0,0.002457,0.350785
7,lc3,None,1618.0,546.0,-0.010350,0.337454
8,le2,Close,220.0,89.0,-0.087570,0.404545
9,le2,Far,194.0,78.0,0.077998,0.402062
10,le2,None,1306.0,460.0,-0.026749,0.352221
11,lw3,Close,1399.0,516.0,0.020525,0.368835
12,lw3,Far,1009.0,305.0,-0.024551,0.302279
13,lw3,None,6412.0,2136.0,-0.003926,0.333125
14,paint2,Close,1288.0,545.0,0.012203,0.423137
15,paint2,Far,864.0,352.0,-0.008071,0.407407
16,paint2,None,6525.0,2631.0,0.001740,0.403218
17,rb2,Close,206.0,89.0,0.061144,0.432039
18,rb2,Far,176.0,58.0,-0.019792,0.329545
19,rb2,None,719.0,241.0,-0.016659,0.335188
20,rc3,Close,138.0,50.0,-0.118814,0.362319
21,rc3,Far,87.0,28.0,-0.065716,0.321839
22,rc3,None,1275.0,488.0,0.048019,0.382745
23,re2,Close,145.0,48.0,-0.006563,0.331034
24,re2,Far,101.0,42.0,0.128089,0.415842
25,re2,None,1127.0,419.0,0.029566,0.371783
26,rw3,Close,1161.0,397.0,-0.021407,0.341947
27,rw3,Far,826.0,282.0,0.013280,0.341404
28,rw3,None,5423.0,1858.0,-0.005352,0.342615
29,tok3,Close,1227.0,419.0,0.018111,0.341483
30,tok3,Far,828.0,261.0,-0.019975,0.315217
31,tok3,None,5714.0,1897.0,0.004029,0.331992

In [127]:
by_type_no_zone

  arena_Type of Wall  w_mean_diff
0                Mix    -0.001718
1              Whole    -0.008385
2                NaN    -0.000828

In [128]:
by_type

   zones13 arena_Type of Wall  w_mean_diff
0     atr2                Mix    -0.065392
1     atr2              Whole     0.012262
2     atr2                NaN     0.037231
3   heave3                Mix     0.019231
4   heave3              Whole    -0.144828
5   heave3                NaN     0.053030
6      lb2                Mix    -0.018547
7      lb2              Whole     0.020458
8      lb2                NaN    -0.039048
9      lc3                Mix    -0.005221
10     lc3              Whole    -0.039883
11     lc3                NaN    -0.013969
12     le2                Mix     0.003361
13     le2              Whole    -0.005966
14     le2                NaN     0.004670
15     lw3                Mix    -0.005461
16     lw3              Whole    -0.003823
17     lw3                NaN     0.008306
18  paint2                Mix     0.000268
19  paint2              Whole     0.004523
20  paint2                NaN     0.001002
21     rb2                Mix    -0.044258
22     rb2              Whole    -0.007419
23     rb2                NaN    -0.020485
24     rc3                Mix    -0.016456
25     rc3              Whole    -0.007597
26     rc3                NaN     0.024469
27     re2                Mix     0.073859
28     re2              Whole    -0.036042
29     re2                NaN    -0.012391
30     rw3                Mix     0.012517
31     rw3              Whole    -0.026947
32     rw3                NaN    -0.006745
33    tok3                Mix    -0.003376
34    tok3              Whole     0.004683
35    tok3                NaN     0.000055

In [129]:
by_type.groupby("arena_Type of Wall", dropna=False).sum()["w_mean_diff"]

arena_Type of Wall
Mix     -0.049473
Whole   -0.230578
NaN      0.036126
Name: w_mean_diff, dtype: float64

In [98]:
by_type

   zones13 arena_Type of Wall  w_mean_diff
0     atr2                Mix    -0.065392
1     atr2              Whole     0.012262
2     atr2                NaN     0.037231
3   heave3                Mix     0.019231
4   heave3              Whole    -0.144828
5   heave3                NaN     0.053030
6      lb2                Mix    -0.018547
7      lb2              Whole     0.020458
8      lb2                NaN    -0.039048
9      lc3                Mix    -0.005221
10     lc3              Whole    -0.039883
11     lc3                NaN    -0.013969
12     le2                Mix     0.003361
13     le2              Whole    -0.005966
14     le2                NaN     0.004670
15     lw3                Mix    -0.005461
16     lw3              Whole    -0.003823
17     lw3                NaN     0.008306
18  paint2                Mix     0.000268
19  paint2              Whole     0.004523
20  paint2                NaN     0.001002
21     rb2                Mix    -0.044258
22     rb2              Whole    -0.007419
23     rb2                NaN    -0.020485
24     rc3                Mix    -0.016456
25     rc3              Whole    -0.007597
26     rc3                NaN     0.024469
27     re2                Mix     0.073859
28     re2              Whole    -0.036042
29     re2                NaN    -0.012391
30     rw3                Mix     0.012517
31     rw3              Whole    -0.026947
32     rw3                NaN    -0.006745
33    tok3                Mix    -0.003376
34    tok3              Whole     0.004683
35    tok3                NaN     0.000055

In [130]:
zone_with_similar

,homeMarket,arena_Arena,season,zones13,side,similar_team,attempts,makes,FG_pct,arena_Side,arena_Distance,arena_Type of Wall,arena_Left_Wall,arena_Right_Wall,arena_Left_Wall_Distance,arena_Right_Wall_Distance,arena_Left_Wall_Type,arena_Right_Wall_Type,sim_team,FG_pct_similar,sim_attempts,diff_FG_pct
0,Air Force,Clune Arena,2021,atr2,LEFT,Wyoming,13,6,0.461538,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,1.000000,1.0,-0.538462
1,Air Force,Clune Arena,2021,atr2,RIGHT,Wyoming,12,6,0.500000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.400000,5.0,0.100000
2,Air Force,Clune Arena,2021,heave3,RIGHT,Wyoming,1,0,0.000000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.000000,1.0,0.000000
3,Air Force,Clune Arena,2021,lb2,LEFT,Wyoming,10,6,0.600000,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.600000,5.0,0.000000
4,Air Force,Clune Arena,2021,lb2,RIGHT,Wyoming,11,2,0.181818,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN,Wyoming,0.600000,5.0,-0.418182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3304,Yale,John J. Lee Amphitheater,2025,re2,RIGHT,Brown,4,0,0.000000,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.375000,8.0,-0.375000
3305,Yale,John J. Lee Amphitheater,2025,rw3,LEFT,Brown,44,17,0.386364,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.260870,23.0,0.125494
3306,Yale,John J. Lee Amphitheater,2025,rw3,RIGHT,Brown,34,13,0.382353,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.466667,15.0,-0.084314
3307,Yale,John J. Lee Amphitheater,2025,tok3,LEFT,Brown,31,4,0.129032,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.285714,21.0,-0.156682
3308,Yale,John J. Lee Amphitheater,2025,tok3,RIGHT,Brown,36,12,0.333333,Both,Far,Mix,True,True,Far,Far,Mix,Mix,Brown,0.241379,29.0,0.091954