In [46]:
import pandas as pd
import numpy as np

# Cleaning

In [5]:
shots_df = pd.read_csv("pbp_shots.csv")
shots_df

,competitionId,gameId,gameDate,homeId,homeMarket,awayId,awayMarket,actionNumber,secsIntoGame,teamId,...,subType,success,side,shotDist,zones6,zones13,x,y,xGs,yGs
0,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,8,40.0,104316,...,jumpshot,False,LEFT,23.816,atb3,lw3,7.0,26.155622,7.0,25.38
1,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,10,52.0,103992,...,stepbackjumpshot,True,RIGHT,15.719,mid2,re2,28.0,26.320000,28.0,26.32
2,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,11,80.0,104316,...,jumpshot,False,LEFT,24.033,c3,rc3,48.0,34.780000,48.0,34.78
3,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,19,122.0,103992,...,jumpshot,False,RIGHT,25.014,atb3,rw3,41.0,22.522455,41.0,21.62
4,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,28,162.0,104316,...,jumpshot,False,LEFT,23.432,atb3,lw3,7.5,26.167519,7.5,25.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289718,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,344,1926.0,104353,...,layup,False,RIGHT,1.073,atr2,atr2,26.0,41.360000,26.0,41.36
289719,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,348,1931.0,104353,...,tipinlayup,True,RIGHT,0.390,atr2,atr2,25.0,41.360000,25.0,41.36
289720,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,400,2222.0,103395,...,drivinglayup,True,LEFT,3.377,atr2,atr2,27.5,39.480000,27.5,39.48
289721,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,411,2275.0,104353,...,layup,False,RIGHT,4.394,atr2,atr2,22.0,38.540000,22.0,38.54
289722,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,430,2366.1,104353,...,layup,True,RIGHT,10.576,paint2,paint2,21.0,31.960000,21.0,31.96

In [6]:
comp_to_season = {
    27693: 2021,
    30629: 2022,
    33533: 2023,
    36046: 2024,
    38409: 2025
}
shots_df["season"] = shots_df["competitionId"].map(comp_to_season)

In [7]:
shots_df

,competitionId,gameId,gameDate,homeId,homeMarket,awayId,awayMarket,actionNumber,secsIntoGame,teamId,...,success,side,shotDist,zones6,zones13,x,y,xGs,yGs,season
0,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,8,40.0,104316,...,False,LEFT,23.816,atb3,lw3,7.0,26.155622,7.0,25.38,2025
1,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,10,52.0,103992,...,True,RIGHT,15.719,mid2,re2,28.0,26.320000,28.0,26.32,2025
2,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,11,80.0,104316,...,False,LEFT,24.033,c3,rc3,48.0,34.780000,48.0,34.78,2025
3,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,19,122.0,103992,...,False,RIGHT,25.014,atb3,rw3,41.0,22.522455,41.0,21.62,2025
4,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,28,162.0,104316,...,False,LEFT,23.432,atb3,lw3,7.5,26.167519,7.5,25.38,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289718,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,344,1926.0,104353,...,False,RIGHT,1.073,atr2,atr2,26.0,41.360000,26.0,41.36,2025
289719,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,348,1931.0,104353,...,True,RIGHT,0.390,atr2,atr2,25.0,41.360000,25.0,41.36,2025
289720,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,400,2222.0,103395,...,True,LEFT,3.377,atr2,atr2,27.5,39.480000,27.5,39.48,2025
289721,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,411,2275.0,104353,...,False,RIGHT,4.394,atr2,atr2,22.0,38.540000,22.0,38.54,2025
289722,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,430,2366.1,104353,...,True,RIGHT,10.576,paint2,paint2,21.0,31.960000,21.0,31.96,2025

In [8]:
shots_df["homeMarket"].unique()

array(['East Texas A&M', 'SFA', 'Southeastern La.', 'Lamar University',
       'New Orleans', 'UIW', 'A&M-Corpus Christi', 'Northwestern St.',
       'McNeese', 'Houston Christian', 'Nicholls', 'Central Ark.',
       'Cal Poly', 'Sam Houston', 'UTRGV', 'Gonzaga', 'BYU', 'Wyoming',
       'Air Force', 'Abilene Christian', 'Boise St.', 'San Francisco',
       'Pacific', 'Portland', 'New Mexico', "Saint Mary's (CA)",
       'Colorado St.', 'Hawaii', 'Santa Clara', 'Utah St.', 'UC Irvine',
       'San Jose St.', 'UNLV', 'Fresno St.', 'San Diego St.', 'Nevada',
       'Princeton', 'Pepperdine', 'San Diego', 'LMU (CA)',
       'Cal St. Fullerton', 'UC Santa Barbara', 'CSU Bakersfield', 'CSUN',
       'Long Beach St.', 'UC San Diego', 'Washington St.', 'Brown',
       'Dartmouth', 'Columbia', 'Cornell', 'Yale', 'Penn', 'Harvard',
       'Oregon St.', 'UC Davis', 'UC Riverside'], dtype=object)

In [9]:
jump_shots_list = ['jumpshot', 'stepbackjumpshot', 'hookshot',
       'floatingjumpshot', 'pullupjumpshot',
       'turnaroundjumpshot']

In [10]:
jump_shots_df = shots_df[shots_df["subType"].isin(jump_shots_list)]
jump_shots_df

,competitionId,gameId,gameDate,homeId,homeMarket,awayId,awayMarket,actionNumber,secsIntoGame,teamId,...,success,side,shotDist,zones6,zones13,x,y,xGs,yGs,season
0,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,8,40.0,104316,...,False,LEFT,23.816,atb3,lw3,7.0,26.155622,7.0,25.38,2025
1,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,10,52.0,103992,...,True,RIGHT,15.719,mid2,re2,28.0,26.320000,28.0,26.32,2025
2,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,11,80.0,104316,...,False,LEFT,24.033,c3,rc3,48.0,34.780000,48.0,34.78,2025
3,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,19,122.0,103992,...,False,RIGHT,25.014,atb3,rw3,41.0,22.522455,41.0,21.62,2025
4,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,28,162.0,104316,...,False,LEFT,23.432,atb3,lw3,7.5,26.167519,7.5,25.38,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289708,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,258,1482.0,103395,...,False,LEFT,25.577,atb3,rw3,39.5,20.680000,39.5,20.68,2025
289709,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,264,1517.0,103395,...,False,LEFT,8.051,paint2,paint2,26.5,33.840000,26.5,33.84,2025
289710,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,268,1547.0,104353,...,True,RIGHT,5.306,paint2,paint2,26.5,36.660000,26.5,36.66,2025
289714,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,310,1761.0,104353,...,False,RIGHT,17.339,mid2,le2,24.0,24.440000,24.0,24.44,2025
289716,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,320,1811.0,104353,...,False,RIGHT,25.864,atb3,rw3,40.0,20.680000,40.0,20.68,2025

In [27]:
teamdrtg = pd.read_csv("teamdrtg.csv")
teamdrtg

,team,adjde,Year,conf,similar_team,similar_adjde,adjde_diff
0,Gonzaga,90.939675,2021,WCC,Saint Mary's (CA),90.282644,0.657031
1,San Diego St.,91.509520,2021,MWC,Utah St.,90.357772,1.151748
2,BYU,93.983974,2021,WCC,Gonzaga,90.939675,3.044299
3,Utah St.,90.357772,2021,MWC,San Diego St.,91.509520,1.151748
4,Boise St.,96.928888,2021,MWC,Colorado St.,97.810866,0.881978
...,...,...,...,...,...,...,...
240,Penn,116.031617,2025,Ivy,Columbia,116.571406,0.539789
241,Long Beach St.,114.062760,2025,BW,CSU Bakersfield,113.225810,0.836950
242,East Texas A&M,111.104067,2025,Slnd,UIW,111.520014,0.415947
243,New Orleans,117.684376,2025,Slnd,UIW,111.520014,6.164362
244,Cal St. Fullerton,112.410545,2025,BW,CSU Bakersfield,113.225810,0.815265

In [24]:
pd.set_option('display.max_columns', None)

In [28]:
drtg_pd = jump_shots_df.merge(
    teamdrtg,
    how="left",
    left_on=["homeMarket", "season"],
    right_on=["team", "Year"]
)
drtg_pd

,competitionId,gameId,gameDate,homeId,homeMarket,awayId,awayMarket,actionNumber,secsIntoGame,teamId,teamMarket,playerId,fullName,actionType,subType,success,side,shotDist,zones6,zones13,x,y,xGs,yGs,season,team,adjde,Year,conf,similar_team,similar_adjde,adjde_diff
0,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,8,40.0,104316,East Texas A&M,1582871,Josh Taylor,3pt,jumpshot,False,LEFT,23.816,atb3,lw3,7.0,26.155622,7.0,25.38,2025,East Texas A&M,111.104067,2025,Slnd,UIW,111.520014,0.415947
1,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,10,52.0,103992,Nicholls,1700052,Byron Ireland,2pt,stepbackjumpshot,True,RIGHT,15.719,mid2,re2,28.0,26.320000,28.0,26.32,2025,East Texas A&M,111.104067,2025,Slnd,UIW,111.520014,0.415947
2,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,11,80.0,104316,East Texas A&M,2345896,Mykol Sanchez-Vega,3pt,jumpshot,False,LEFT,24.033,c3,rc3,48.0,34.780000,48.0,34.78,2025,East Texas A&M,111.104067,2025,Slnd,UIW,111.520014,0.415947
3,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,19,122.0,103992,Nicholls,1695270,Michael Gray Jr.,3pt,jumpshot,False,RIGHT,25.014,atb3,rw3,41.0,22.522455,41.0,21.62,2025,East Texas A&M,111.104067,2025,Slnd,UIW,111.520014,0.415947
4,38409,2549421,2025-01-06,104316,East Texas A&M,103992,Nicholls,28,162.0,104316,East Texas A&M,1605923,Khaliq Abdul-Mateen,3pt,jumpshot,False,LEFT,23.432,atb3,lw3,7.5,26.167519,7.5,25.38,2025,East Texas A&M,111.104067,2025,Slnd,UIW,111.520014,0.415947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180782,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,258,1482.0,103395,Cal Poly,2318757,Cayden Ward,3pt,jumpshot,False,LEFT,25.577,atb3,rw3,39.5,20.680000,39.5,20.68,2025,UC Irvine,97.338793,2025,BW,UC San Diego,97.540056,0.201263
180783,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,264,1517.0,103395,Cal Poly,1925537,"Aaron Price, Jr.",2pt,turnaroundjumpshot,False,LEFT,8.051,paint2,paint2,26.5,33.840000,26.5,33.84,2025,UC Irvine,97.338793,2025,BW,UC San Diego,97.540056,0.201263
180784,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,268,1547.0,104353,UC Irvine,2111158,Jurian Dixon,2pt,floatingjumpshot,True,RIGHT,5.306,paint2,paint2,26.5,36.660000,26.5,36.66,2025,UC Irvine,97.338793,2025,BW,UC San Diego,97.540056,0.201263
180785,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,310,1761.0,104353,UC Irvine,2113896,Myles Che,2pt,pullupjumpshot,False,RIGHT,17.339,mid2,le2,24.0,24.440000,24.0,24.44,2025,UC Irvine,97.338793,2025,BW,UC San Diego,97.540056,0.201263
180786,38409,2531544,2025-01-18,104353,UC Irvine,103395,Cal Poly,320,1811.0,104353,UC Irvine,1603054,Devin Tillis,3pt,jumpshot,False,RIGHT,25.864,atb3,rw3,40.0,20.680000,40.0,20.68,2025,UC Irvine,97.338793,2025,BW,UC San Diego,97.540056,0.201263

In [30]:
shots_less_info_df=drtg_pd.drop(columns=["competitionId","gameDate","homeId","awayId","actionNumber","teamId","playerId","fullName","x","y","xGs","yGs","adjde","similar_adjde","adjde_diff"])

In [37]:
shots_less_info_df

,gameId,homeMarket,awayMarket,secsIntoGame,teamMarket,actionType,subType,success,side,shotDist,zones6,zones13,season,team,Year,conf,similar_team
0,2549421,East Texas A&M,Nicholls,40.0,East Texas A&M,3pt,jumpshot,False,LEFT,23.816,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW
1,2549421,East Texas A&M,Nicholls,52.0,Nicholls,2pt,stepbackjumpshot,True,RIGHT,15.719,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW
2,2549421,East Texas A&M,Nicholls,80.0,East Texas A&M,3pt,jumpshot,False,LEFT,24.033,c3,rc3,2025,East Texas A&M,2025,Slnd,UIW
3,2549421,East Texas A&M,Nicholls,122.0,Nicholls,3pt,jumpshot,False,RIGHT,25.014,atb3,rw3,2025,East Texas A&M,2025,Slnd,UIW
4,2549421,East Texas A&M,Nicholls,162.0,East Texas A&M,3pt,jumpshot,False,LEFT,23.432,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180782,2531544,UC Irvine,Cal Poly,1482.0,Cal Poly,3pt,jumpshot,False,LEFT,25.577,atb3,rw3,2025,UC Irvine,2025,BW,UC San Diego
180783,2531544,UC Irvine,Cal Poly,1517.0,Cal Poly,2pt,turnaroundjumpshot,False,LEFT,8.051,paint2,paint2,2025,UC Irvine,2025,BW,UC San Diego
180784,2531544,UC Irvine,Cal Poly,1547.0,UC Irvine,2pt,floatingjumpshot,True,RIGHT,5.306,paint2,paint2,2025,UC Irvine,2025,BW,UC San Diego
180785,2531544,UC Irvine,Cal Poly,1761.0,UC Irvine,2pt,pullupjumpshot,False,RIGHT,17.339,mid2,le2,2025,UC Irvine,2025,BW,UC San Diego
180786,2531544,UC Irvine,Cal Poly,1811.0,UC Irvine,3pt,jumpshot,False,RIGHT,25.864,atb3,rw3,2025,UC Irvine,2025,BW,UC San Diego

In [49]:
away_shots_df = shots_less_info_df[shots_less_info_df["homeMarket"]!=shots_less_info_df["teamMarket"]]

In [95]:
def check_half_and_side(away_shots_df, team_col="teamMarket"):
    df = away_shots_df.copy()


    df["half"] = np.select(
        [df["secsIntoGame"] <= 1200, df["secsIntoGame"] <= 2400],
        [1, 2],
        default=3
    )


    half_max = (
        df.groupby(["gameId", "half"])["secsIntoGame"]
          .max()
          .unstack(fill_value=np.nan)
    )
    bad_time_first  = half_max[half_max.get(1, pd.Series(dtype=float)) > 1200]
    bad_time_second = half_max[half_max.get(2, pd.Series(dtype=float)) <= 1200]

    side_nunique = (
        df.groupby(["gameId", team_col, "half"])["side"]
          .nunique(dropna=True)
          .rename("num_sides")
    )
    viol_side = side_nunique[side_nunique > 1]


    def first_mode(s: pd.Series):
        s = s.dropna()
        if s.empty: return np.nan
        m = s.mode()
        return m.iloc[0] if not m.empty else np.nan

    primary_side = (
        df.groupby(["gameId", team_col, "half"])["side"]
          .agg(first_mode)
          .rename("primary_side")
          .reset_index()
    )

    df = df.merge(primary_side, on=["gameId", team_col, "half"], how="left")
    df["side_mismatch"] = (df["side"] != df["primary_side"]) & df["primary_side"].notna()


    mismatched_rows = df[df["side_mismatch"]].copy()


    clean_df = df[~(df.index.isin(mismatched_rows.index) & df["half"].isin([1, 2]))].copy()

    return {
        "half_max_per_game": half_max,
        "bad_time_first": bad_time_first,
        "bad_time_second": bad_time_second,
        "viol_side_counts": viol_side,
        "mismatched_rows": mismatched_rows,
        "df_with_primary": df,
        "clean_df": clean_df,                  
    }

In [96]:
res = check_half_and_side(away_shots_df, team_col="teamMarket")
clean_away_shots_df = res["clean_df"]  # OT kept, bad H1/H2 shots dropped

In [97]:
clean_away_shots_df

,gameId,homeMarket,awayMarket,secsIntoGame,teamMarket,actionType,subType,success,side,shotDist,zones6,zones13,season,team,Year,conf,similar_team,half,primary_side,side_mismatch
0,2549421,East Texas A&M,Nicholls,52.0,Nicholls,2pt,stepbackjumpshot,True,RIGHT,15.719,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,RIGHT,False
1,2549421,East Texas A&M,Nicholls,122.0,Nicholls,3pt,jumpshot,False,RIGHT,25.014,atb3,rw3,2025,East Texas A&M,2025,Slnd,UIW,1,RIGHT,False
2,2549421,East Texas A&M,Nicholls,391.0,Nicholls,2pt,pullupjumpshot,True,RIGHT,11.751,mid2,re2,2025,East Texas A&M,2025,Slnd,UIW,1,RIGHT,False
3,2549421,East Texas A&M,Nicholls,506.0,Nicholls,3pt,jumpshot,False,RIGHT,28.561,atb3,lw3,2025,East Texas A&M,2025,Slnd,UIW,1,RIGHT,False
4,2549421,East Texas A&M,Nicholls,694.0,Nicholls,2pt,turnaroundjumpshot,False,RIGHT,13.229,paint2,paint2,2025,East Texas A&M,2025,Slnd,UIW,1,RIGHT,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90833,2531544,UC Irvine,Cal Poly,1213.0,Cal Poly,3pt,jumpshot,False,LEFT,23.435,atb3,lw3,2025,UC Irvine,2025,BW,UC San Diego,2,LEFT,False
90834,2531544,UC Irvine,Cal Poly,1354.0,Cal Poly,3pt,jumpshot,True,LEFT,26.160,atb3,tok3,2025,UC Irvine,2025,BW,UC San Diego,2,LEFT,False
90835,2531544,UC Irvine,Cal Poly,1407.0,Cal Poly,2pt,pullupjumpshot,True,LEFT,11.017,paint2,paint2,2025,UC Irvine,2025,BW,UC San Diego,2,LEFT,False
90836,2531544,UC Irvine,Cal Poly,1482.0,Cal Poly,3pt,jumpshot,False,LEFT,25.577,atb3,rw3,2025,UC Irvine,2025,BW,UC San Diego,2,LEFT,False
90837,2531544,UC Irvine,Cal Poly,1517.0,Cal Poly,2pt,turnaroundjumpshot,False,LEFT,8.051,paint2,paint2,2025,UC Irvine,2025,BW,UC San Diego,2,LEFT,False

In [98]:
clean_away_shots_df.to_csv("shots.csv",index=False)

In [109]:
cc_shots = clean_away_shots_df[clean_away_shots_df["homeMarket"]=="A&M-Corpus Christi"]
cc_shots.to_csv("cc_shots.csv",index=False)

In [108]:
cc_shots

,gameId,homeMarket,awayMarket,secsIntoGame,teamMarket,actionType,subType,success,side,shotDist,zones6,zones13,season,team,Year,conf,similar_team,half,primary_side,side_mismatch
100,1984957,A&M-Corpus Christi,Northwestern St.,124.0,Northwestern St.,2pt,jumpshot,False,LEFT,20.004,mid2,rb2,2022,A&M-Corpus Christi,2022,Slnd,Nicholls,1,LEFT,False
101,1984957,A&M-Corpus Christi,Northwestern St.,352.0,Northwestern St.,2pt,jumpshot,False,LEFT,15.822,mid2,le2,2022,A&M-Corpus Christi,2022,Slnd,Nicholls,1,LEFT,False
102,1984957,A&M-Corpus Christi,Northwestern St.,520.0,Northwestern St.,3pt,jumpshot,True,LEFT,23.411,atb3,lw3,2022,A&M-Corpus Christi,2022,Slnd,Nicholls,1,LEFT,False
103,1984957,A&M-Corpus Christi,Northwestern St.,585.0,Northwestern St.,2pt,jumpshot,True,LEFT,17.792,mid2,rb2,2022,A&M-Corpus Christi,2022,Slnd,Nicholls,1,LEFT,False
104,1984957,A&M-Corpus Christi,Northwestern St.,665.0,Northwestern St.,3pt,jumpshot,False,LEFT,24.284,atb3,rw3,2022,A&M-Corpus Christi,2022,Slnd,Nicholls,1,LEFT,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83629,2184087,A&M-Corpus Christi,CSU Bakersfield,1296.0,CSU Bakersfield,2pt,jumpshot,False,RIGHT,18.312,mid2,re2,2023,A&M-Corpus Christi,2023,Slnd,Nicholls,2,RIGHT,False
83630,2184087,A&M-Corpus Christi,CSU Bakersfield,1620.0,CSU Bakersfield,3pt,stepbackjumpshot,True,RIGHT,23.112,c3,rc3,2023,A&M-Corpus Christi,2023,Slnd,Nicholls,2,RIGHT,False
83631,2184087,A&M-Corpus Christi,CSU Bakersfield,1745.0,CSU Bakersfield,2pt,pullupjumpshot,False,RIGHT,18.950,mid2,le2,2023,A&M-Corpus Christi,2023,Slnd,Nicholls,2,RIGHT,False
83632,2184087,A&M-Corpus Christi,CSU Bakersfield,1851.0,CSU Bakersfield,3pt,jumpshot,False,RIGHT,23.128,c3,rc3,2023,A&M-Corpus Christi,2023,Slnd,Nicholls,2,RIGHT,False
83633,2184087,A&M-Corpus Christi,CSU Bakersfield,1878.0,CSU Bakersfield,2pt,turnaroundjumpshot,True,RIGHT,6.523,mid2,rb2,2023,A&M-Corpus Christi,2023,Slnd,Nicholls,2,RIGHT,False

## Test statistics

In [13]:
ucsd_home_game_jump_shots = jump_shots_df[jump_shots_df["homeMarket"] == "UC San Diego"]
ucsd_home_game_jump_shots

,competitionId,gameId,gameDate,homeId,homeMarket,awayId,awayMarket,actionNumber,secsIntoGame,teamId,...,success,side,shotDist,zones6,zones13,x,y,xGs,yGs,season
57992,36046,2337410,2023-12-01,104355,UC San Diego,104199,San Diego St.,90,694.0,104199,...,False,LEFT,25.562,atb3,rw3,38.0,19.740000,38.0,19.74,2024
57993,36046,2337410,2023-12-01,104355,UC San Diego,104199,San Diego St.,168,1228.0,104199,...,True,RIGHT,24.310,atb3,tok3,20.5,17.860000,20.5,17.86,2024
57995,36046,2337410,2023-12-01,104355,UC San Diego,104199,San Diego St.,254,1852.0,104199,...,False,RIGHT,18.706,mid2,lb2,7.0,36.660000,7.0,36.66,2024
59999,36046,2337410,2023-12-01,104355,UC San Diego,104199,San Diego St.,45,304.0,104199,...,True,LEFT,24.758,atb3,tok3,18.5,17.860000,18.5,17.86,2024
60000,36046,2337410,2023-12-01,104355,UC San Diego,104199,San Diego St.,49,329.0,104199,...,False,LEFT,24.331,atb3,lw3,7.0,25.380000,7.0,25.38,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289686,33533,2194141,2023-02-04,104355,UC San Diego,103389,CSU Bakersfield,331,2604.0,103389,...,True,RIGHT,14.851,mid2,rb2,39.5,38.540000,39.5,38.54,2023
289687,33533,2194141,2023-02-04,104355,UC San Diego,103389,CSU Bakersfield,341,2642.1,104355,...,True,LEFT,24.677,atb3,lw3,5.0,27.295265,5.0,26.32,2023
289689,33533,2194141,2023-02-04,104355,UC San Diego,103389,CSU Bakersfield,345,2648.4,104355,...,False,LEFT,26.239,atb3,lw3,11.5,19.250016,11.5,17.86,2023
289690,33533,2194141,2023-02-04,104355,UC San Diego,103389,CSU Bakersfield,361,2669.5,104355,...,False,LEFT,25.535,atb3,tok3,20.5,16.614412,20.5,15.04,2023
289691,33533,2194141,2023-02-04,104355,UC San Diego,103389,CSU Bakersfield,368,2677.4,104355,...,False,LEFT,26.782,atb3,lw3,12.0,18.334464,12.0,16.92,2023

In [14]:
ucsd_home_game_jump_shots_left = ucsd_home_game_jump_shots[(ucsd_home_game_jump_shots["side"] == "LEFT") & (ucsd_home_game_jump_shots["teamId"]!=104355)]["success"].mean()
ucsd_home_game_jump_shots_left

np.float64(0.35501653803748623)

In [15]:
ucsd_home_game_jump_shots_right = ucsd_home_game_jump_shots[(ucsd_home_game_jump_shots["side"] == "RIGHT") & (ucsd_home_game_jump_shots["teamId"]!=104355)]["success"].mean()
ucsd_home_game_jump_shots_right

np.float64(0.37167070217917675)

In [16]:
ucsb_home_game_jump_shots = jump_shots_df[jump_shots_df["homeMarket"] == "UC Santa Barbara"]
ucsb_home_game_jump_shots

,competitionId,gameId,gameDate,homeId,homeMarket,awayId,awayMarket,actionNumber,secsIntoGame,teamId,...,success,side,shotDist,zones6,zones13,x,y,xGs,yGs,season
39074,38409,2555358,2024-11-13,104356,UC Santa Barbara,103631,Fresno St.,22,104.0,103631,...,True,LEFT,9.907,mid2,rb2,33.5,36.660000,33.5,36.66,2025
39075,38409,2555358,2024-11-13,104356,UC Santa Barbara,103631,Fresno St.,25,118.0,103631,...,False,LEFT,5.261,paint2,paint2,22.0,37.428000,22.0,36.66,2025
39077,38409,2555358,2024-11-13,104356,UC Santa Barbara,103631,Fresno St.,50,274.0,103631,...,False,LEFT,23.864,c3,lc3,1.5,37.600000,1.5,37.60,2025
39078,38409,2555358,2024-11-13,104356,UC Santa Barbara,103631,Fresno St.,82,441.0,103631,...,False,LEFT,24.078,atb3,tok3,28.0,17.860000,28.0,17.86,2025
39080,38409,2555358,2024-11-13,104356,UC Santa Barbara,103631,Fresno St.,103,604.0,103631,...,True,LEFT,11.842,paint2,paint2,25.0,29.908000,25.0,29.14,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289090,33533,2181981,2022-11-11,104356,UC Santa Barbara,103631,Fresno St.,269,1992.0,104356,...,False,LEFT,14.123,mid2,rb2,38.5,37.600000,38.5,37.60,2023
289092,33533,2181981,2022-11-11,104356,UC Santa Barbara,103631,Fresno St.,287,2106.0,104356,...,True,LEFT,15.368,mid2,le2,15.0,30.080000,15.0,30.08,2023
289095,33533,2181981,2022-11-11,104356,UC Santa Barbara,103631,Fresno St.,313,2283.0,104356,...,False,LEFT,24.246,atb3,lw3,2.5,32.714949,2.5,31.96,2023
289096,33533,2181981,2022-11-11,104356,UC Santa Barbara,103631,Fresno St.,320,2329.0,104356,...,False,LEFT,10.238,mid2,lb2,18.5,33.840000,18.5,33.84,2023
289097,33533,2181981,2022-11-11,104356,UC Santa Barbara,103631,Fresno St.,327,2346.5,104356,...,True,LEFT,13.358,mid2,re2,31.5,30.080000,31.5,30.08,2023

In [17]:
ucsb_home_game_jump_shots_left = ucsb_home_game_jump_shots[(ucsb_home_game_jump_shots["side"] == "LEFT") & (ucsb_home_game_jump_shots["teamId"]!=104356)]["success"].mean()
ucsb_home_game_jump_shots_left

np.float64(0.3747663551401869)

In [18]:
ucsb_home_game_jump_shots_right = ucsb_home_game_jump_shots[(ucsb_home_game_jump_shots["side"] == "RIGHT") & (ucsb_home_game_jump_shots["teamId"]!=104356)]["success"].mean()
ucsb_home_game_jump_shots_right

np.float64(0.3578838174273859)

In [19]:
ucr_home_game_jump_shots = jump_shots_df[jump_shots_df["homeMarket"] == "UC Riverside"]
ucr_home_game_jump_shots
ucr_home_game_jump_shots_left = ucr_home_game_jump_shots[(ucr_home_game_jump_shots["side"] == "LEFT") & (ucr_home_game_jump_shots["teamId"]!=104354)]["success"].mean()
ucr_home_game_jump_shots_left

np.float64(0.3655913978494624)

In [20]:
ucr_home_game_jump_shots_right = ucr_home_game_jump_shots[(ucr_home_game_jump_shots["side"] == "RIGHT") & (ucr_home_game_jump_shots["teamId"]!=104354)]["success"].mean()
ucr_home_game_jump_shots_right

np.float64(0.3745283018867924)

In [21]:
uci_home_game_jump_shots = jump_shots_df[jump_shots_df["homeMarket"] == "UC Irvine"]
uci_home_game_jump_shots_left = uci_home_game_jump_shots[(uci_home_game_jump_shots["side"] == "LEFT") & (uci_home_game_jump_shots["teamId"]!=104353)]["success"].mean()
uci_home_game_jump_shots_left

np.float64(0.33899821109123435)

In [22]:
uci_home_game_jump_shots_right = uci_home_game_jump_shots[(uci_home_game_jump_shots["side"] == "RIGHT") & (uci_home_game_jump_shots["teamId"]!=104353)]["success"].mean()
uci_home_game_jump_shots_right

np.float64(0.34987384356602186)